In [74]:
import pandas as pd
import os
os.chdir('/Users/caicaiqijun/智慧牙/智慧芽/Discover/指标')
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://company:company@192.168.16.244/company_v23',echo=False)
from data_nlp_nameclean.clean.cleaning import cleanup_entity

# TFFI TEST

In [87]:
os.chdir('/Users/caicaiqijun/智慧牙/数据/Discover/测试集')

In [93]:
DIS_TEST=pd.read_excel('DIS_TEST样本.xlsx')
DIS_TEST

,entity_id,source,label,source_list,ans_id,company_name
0,cfbb57974cd08351d857499d4883043b,PCT多,1,['PCT多'],e34a0d1b-cea2-4a70-b97b-c3656383e86d,"Rosemount Analytical, Inc."
1,f8648ab83bf6f732a8c5818efebc7675,PCT多,1,['PCT多'],d4f2e2ed-d3ea-498f-b825-8ed8f15fdbff,Systema SpA
2,f79df5f0e6094ed5b0601c85cb78666d,PCT多,1,['PCT多'],dfec6f49-a66b-4ec7-89d1-3d2b673ec237,EPC Engineering & Technologies GmbH
3,4df4474dbc712946a885411659235be8,PCT多,1,"['PCT多', '近两年授权发明专利数量多']",823e877f-6bab-4f18-b129-052be459fdc2,"Rovi Guides, Inc."
4,7000904ac25cfa44b31f54445e8084f6,PCT多,1,['PCT多'],21ab51d4-7069-4d29-a03e-f259c59cde29,"Tobira Therapeutics, Inc."
...,...,...,...,...,...,...
3829,245a12bffdd608bfc489ab3c6d41cd37,成立时间长-专利少-药,0,['成立时间长-专利少-药'],7141f99c-e0e8-4a99-a5d7-ae71023a0fd9,汕头市新侨药用防粘纸科技有限公司
3830,6a0f2f8a394ec87f157abaae71bc9c3a,成立时间长-专利少-药,0,['成立时间长-专利少-药'],NaN,成都川力制药有限公司
3831,ccbf98ee1df815ef929e134a320488c1,成立时间长-专利少-药,0,['成立时间长-专利少-药'],4ee6e609-d704-412e-91be-37b66ca28862,中国全聚德（集团）股份有限公司
3832,48d50d2a703d6b1a0080ec5158906245,成立时间长-专利少-药,0,['成立时间长-专利少-药'],NaN,天津新内田制药有限公司
3833,5ecac14f231ecf9865493835418f1b06,成立时间长-专利少-药,0,['成立时间长-专利少-药'],NaN,运盛（成都）医疗科技股份有限公司

In [79]:
company_original['clean_name']=company_original['company_name'].apply(lambda x:cleanup_entity(x))
company_original

/Users/caicaiqijun/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,entity_id,ans_id,company_name,company_id,seic_lv1,seic_lv2,avg_3y_cnt,patenting_growth_ratio,self_cited_by_ratio,invention_stability,...,apno_cnt,qualification,duration,num_members,avg_funding_interval,most_recent_money_q25_formatted,most_recent_time,rounds,money_q25_sum_weighted,clean_name
3,881eb8cbcd67ca12a5149fdd7ba4bdd4,df2ec2a3-6c58-4875-b3ba-803540a39622,杰信达建设发展集团有限公司,8A4B7A386B4F3FDE3EBDE7523F468CD7,其它,其它,0.333333,-0.5,0.0,0.0,...,2,未知,NaN,0,NaN,NaN,NaN,0,NaN,杰信达建设发展集团有限公司
4,5dc8bcc510ff5ec4ca313a2b74d0ecee,5a7fb0af-6a6f-4e10-830a-948baf545a0b,海南航空旅业开发股份有限公司,2BF2F6D0071561771A8616AAFB0EBF9A,其它,其它,0.000000,999.0,0.0,0.0,...,1,未知,NaN,0,NaN,NaN,NaN,0,NaN,海南航空旅业开发股份有限公司
5,ddf9464c1eb2d51ec9e2765184f8515c,3b19bc62-3238-4514-bd48-71fa640b7aff,刺果松（深圳）实业有限公司,A4938B211793F2608FE2B0326062BD55,其它,其它,1.000000,998.0,0.0,0.0,...,3,未知,NaN,0,NaN,NaN,NaN,0,NaN,刺果松深圳实业有限公司
6,8859a51e6a988bb3603d05d42e0cf487,148e6eee-46c3-4837-bdf9-002e3ffebf3d,深圳市世通专利代理事务所（普通合伙）,E510BD7F5517E7098D76A4A959D3CDBA,其它,其它,0.000000,NaN,NaN,NaN,...,0,未知,NaN,0,NaN,NaN,NaN,0,NaN,深圳市世通专利代理事务所普通合伙
10,450003e0ffd0442b2aee919fb6d0aea3,a9250070-85c9-43df-9e42-34190fd23f5a,中山励精艺品家私陶瓷有限公司,E304C92B419AF92E60C48C51A1CFCBD5,其它,其它,0.000000,999.0,0.0,0.0,...,4,未知,NaN,0,NaN,NaN,NaN,0,NaN,中山励精艺品家私陶瓷有限公司
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,D2FC997471DBA4A64CBAB3CB9096ABB0,其它,其它,0.000000,NaN,NaN,NaN,...,0,未知,NaN,0,NaN,NaN,NaN,0,NaN,甘肃股权交易中心股份有限公司
2368319,a4cc033bfe6139f19d3d14ffb7336cf7,3b5a192c-f351-4a95-b001-f5d72206c705,靖江市达克罗涂覆工业有限公司,599535AF30271296992F1449263D7EBB,其它,其它,6.000000,0.5,0.0,0.0,...,35,未知,NaN,0,NaN,NaN,NaN,0,NaN,靖江市达克罗涂覆工业有限公司
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,F09077832F65C370268580D61E7BADBD,其它,其它,0.000000,NaN,NaN,NaN,...,0,未知,NaN,0,NaN,NaN,NaN,0,NaN,上海学点教育科技有限公司
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,2575891F1A32788291C734472B8DDA04,其它,其它,0.000000,NaN,NaN,NaN,...,0,未知,NaN,0,NaN,NaN,NaN,0,NaN,上海奉光园林绿化有限公司
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,5366A5F9DE71781CA63D764EBFD3B700,其它,其它,0.000000,NaN,NaN,NaN,...,0,未知,NaN,0,NaN,NaN,NaN,0,NaN,安徽智农农业设备科技有限公司

In [92]:
DIS_TEST=pd.merge(DIS_TEST,discovery_original[['entity_id','ans_id','company_name','company_id']],on='entity_id')
DIS_TEST.to_excel('DIS_TEST样本.xlsx',encoding='utf-8',index=False)

# discovery_original

In [7]:
discovery_original=pd.read_sql('select * from discovery_original',con=engine)
discovery_original

,entity_id,ans_id,company_name,company_id,seic_lv1,seic_lv2,avg_3y_cnt,patenting_growth_ratio,self_cited_by_ratio,invention_stability,...,inventor_cnt,apno_cnt,qualification,duration,num_members,avg_funding_interval,most_recent_money_q25_formatted,most_recent_time,rounds,money_q25_sum_weighted
0,b62861edc99815f0000170071ffab65d,bc7e38df-d8cb-495a-bce6-b1a4d5de7107,DMW Corp.,None,其它,其它,7.000000,1.04939,0.094862,2.869379,...,23,253,某股,NaN,0,NaN,NaN,NaN,0,NaN
1,b5597feb3c250476966c958c6c79ed5a,f27191f9-6b04-4b59-9c9f-208faa472d28,Corvus Technologies Corp.,None,其它,其它,0.000000,999.00000,0.250000,1.577621,...,0,8,非上市,NaN,0,NaN,NaN,NaN,0,NaN
2,40b9730e1a9698869d3162d648848b6d,c142c003-cd8c-4164-bf2e-04410500501e,CAC Systèmes SA,None,其它,其它,0.000000,999.00000,0.000000,0.000000,...,0,1,非上市,NaN,0,NaN,NaN,NaN,0,NaN
3,881eb8cbcd67ca12a5149fdd7ba4bdd4,df2ec2a3-6c58-4875-b3ba-803540a39622,杰信达建设发展集团有限公司,8A4B7A386B4F3FDE3EBDE7523F468CD7,其它,其它,0.333333,-0.50000,0.000000,0.000000,...,1,2,未知,NaN,0,NaN,NaN,NaN,0,NaN
4,5dc8bcc510ff5ec4ca313a2b74d0ecee,5a7fb0af-6a6f-4e10-830a-948baf545a0b,海南航空旅业开发股份有限公司,2BF2F6D0071561771A8616AAFB0EBF9A,其它,其它,0.000000,999.00000,0.000000,0.000000,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,D2FC997471DBA4A64CBAB3CB9096ABB0,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368319,a4cc033bfe6139f19d3d14ffb7336cf7,3b5a192c-f351-4a95-b001-f5d72206c705,靖江市达克罗涂覆工业有限公司,599535AF30271296992F1449263D7EBB,其它,其它,6.000000,0.50000,0.000000,0.000000,...,7,35,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,F09077832F65C370268580D61E7BADBD,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,2575891F1A32788291C734472B8DDA04,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,5366A5F9DE71781CA63D764EBFD3B700,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN

In [66]:
discovery_original[discovery_original['company_name'].isnull()]

,entity_id,ans_id,company_name,company_id,seic_lv1,seic_lv2,avg_3y_cnt,patenting_growth_ratio,self_cited_by_ratio,invention_stability,...,inventor_cnt,apno_cnt,qualification,duration,num_members,avg_funding_interval,most_recent_money_q25_formatted,most_recent_time,rounds,money_q25_sum_weighted
11,53a2de6712e6edc74452adbb4be90c23,feacce95-27ce-446b-b05f-493753cc1470,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
13,ab94eb67f963546ef59c966a46b5231e,4b2823c9-a58b-4eb5-ae77-2708d9393a06,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
28,80363aa7006af23ebabe68d11e2c3a28,ce3ed400-4cee-4fe9-84fa-18f3dee3eeb4,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,4,未知,NaN,0,NaN,NaN,NaN,0,NaN
35,da920e2d21b1222f5a3fbc335bcdfbcc,a2064957-3213-49fc-811f-ad22a6d16391,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
36,02596a2ed49a349ea29260638fb49210,13ff5c80-c10c-4277-a50b-a7060d379af3,None,None,其它,其它,0.0,NaN,0.0,NaN,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368235,8523b399931204d6700c9bd04e9666ff,1f56b25c-cb11-4a5f-bdf9-b01f106125aa,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368290,41b541db4e78583aa89a349efc08626e,b3c9cb65-58f9-4e99-acd2-1431c29feb9f,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,3,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368292,c426b1d91f469ed97fa20e4af523d4e7,0685e873-c389-407d-a9a8-990f80a3eef8,None,None,其它,其它,0.0,NaN,0.0,NaN,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368305,618df5a88339defba539ea2c4918ac97,f39c1d76-f6bb-4bb9-8b61-58c82b442ca8,None,None,其它,其它,1.0,998.0,0.0,0.0,...,8,5,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368306,e5ccbd70956b655ebf39d8339a90e95b,dd3595f6-07da-407f-a4c4-7e2b5a00e18d,None,None,其它,其它,0.0,999.0,0.0,0.0,...,0,3,未知,NaN,0,NaN,NaN,NaN,0,NaN

In [23]:
company_original=discovery_original[discovery_original['company_id'].notnull()]
company_original

,entity_id,ans_id,company_name,company_id,seic_lv1,seic_lv2,avg_3y_cnt,patenting_growth_ratio,self_cited_by_ratio,invention_stability,...,inventor_cnt,apno_cnt,qualification,duration,num_members,avg_funding_interval,most_recent_money_q25_formatted,most_recent_time,rounds,money_q25_sum_weighted
3,881eb8cbcd67ca12a5149fdd7ba4bdd4,df2ec2a3-6c58-4875-b3ba-803540a39622,杰信达建设发展集团有限公司,8A4B7A386B4F3FDE3EBDE7523F468CD7,其它,其它,0.333333,-0.5,0.0,0.0,...,1,2,未知,NaN,0,NaN,NaN,NaN,0,NaN
4,5dc8bcc510ff5ec4ca313a2b74d0ecee,5a7fb0af-6a6f-4e10-830a-948baf545a0b,海南航空旅业开发股份有限公司,2BF2F6D0071561771A8616AAFB0EBF9A,其它,其它,0.000000,999.0,0.0,0.0,...,0,1,未知,NaN,0,NaN,NaN,NaN,0,NaN
5,ddf9464c1eb2d51ec9e2765184f8515c,3b19bc62-3238-4514-bd48-71fa640b7aff,刺果松（深圳）实业有限公司,A4938B211793F2608FE2B0326062BD55,其它,其它,1.000000,998.0,0.0,0.0,...,1,3,未知,NaN,0,NaN,NaN,NaN,0,NaN
6,8859a51e6a988bb3603d05d42e0cf487,148e6eee-46c3-4837-bdf9-002e3ffebf3d,深圳市世通专利代理事务所（普通合伙）,E510BD7F5517E7098D76A4A959D3CDBA,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
10,450003e0ffd0442b2aee919fb6d0aea3,a9250070-85c9-43df-9e42-34190fd23f5a,中山励精艺品家私陶瓷有限公司,E304C92B419AF92E60C48C51A1CFCBD5,其它,其它,0.000000,999.0,0.0,0.0,...,0,4,未知,NaN,0,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,D2FC997471DBA4A64CBAB3CB9096ABB0,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368319,a4cc033bfe6139f19d3d14ffb7336cf7,3b5a192c-f351-4a95-b001-f5d72206c705,靖江市达克罗涂覆工业有限公司,599535AF30271296992F1449263D7EBB,其它,其它,6.000000,0.5,0.0,0.0,...,7,35,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,F09077832F65C370268580D61E7BADBD,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,2575891F1A32788291C734472B8DDA04,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,5366A5F9DE71781CA63D764EBFD3B700,其它,其它,0.000000,NaN,NaN,NaN,...,0,0,未知,NaN,0,NaN,NaN,NaN,0,NaN

In [39]:
company_original['avg_cited_by_cnt'].max()

340.0

In [13]:
discovery_original.columns

Index(['entity_id', 'ans_id', 'company_name', 'company_id', 'seic_lv1',
       'seic_lv2', 'avg_3y_cnt', 'patenting_growth_ratio',
       'self_cited_by_ratio', 'invention_stability', 'non_design_apno_cnt',
       'active_inventor_ratio', 'granted_invention_cnt_pb_1y',
       'granted_invention_cnt_pb_original_2y', 'apno_cnt_valid_5y',
       'value_sum', 'value_top5_avg', 'avg_remaining_life_span',
       'avg_technology_score', 'value_avg', 'in_examing_ratio',
       'granted_invention_ratio', 'granted_invention_cnt', 'invention_ratio',
       'ip_dependency', 'total_patent_award_score', 'patent_valid_ratio',
       'top5_current_impact_index', 'most_cited_patents_value',
       'external_licensing_cnt', 'core_patents_cited_by_cnt',
       'core_patents_cited_by_ratio', 'avg_cited_by_cnt',
       'joint_application_cnt', 'tech_global_concentration', 'tech_width',
       'country_cnt', 'non_design_pct_apno_cnt', 'joint_applicant_cnt',
       'inventor_cnt', 'apno_cnt', 'qualification', 'duration', 'num_members',
       'avg_funding_interval', 'most_recent_money_q25_formatted',
       'most_recent_time', 'rounds', 'money_q25_sum_weighted'],
      dtype='object')

## apno_cnt

In [12]:
discovery_original.sort_values('apno_cnt',ascending=False)[['entity_id','ans_id','company_name','apno_cnt']]

,entity_id,ans_id,company_name,apno_cnt
2275660,46b0b867cfc33d45cde6bc22e2c1fdfe,50a3383a-0e1c-41ab-a747-bba006345d3f,"Matsushita Sangyo Co., Ltd.",822379
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",697927
2334049,e16094dcb62483c7713bad0a79c31c5b,dadb8b6f-6e98-48d7-b495-f1478564958b,None,574698
1861299,4ccadf73adf70c9bdd1a4205e74c125e,4c2a691c-0636-4a1b-a8ca-909e0b517647,"Canon, Inc.",548682
578572,0e0e87c1511d46c5f7396532dea64e34,7961ed12-1f56-4967-a032-023d2f43d359,Hitachi Ltd.,517218
...,...,...,...,...
406087,8d79107a976311880a30b4aaf24d267e,None,玛西普盈康医疗科技（青岛）有限公司,0
1678617,4b3f5951747222abef23146060ee547f,None,常州市国益净化玻璃设备有限公司,0
406088,ff8739ccbc7739ed14eb52743f050f01,None,真相科技（重庆）有限公司,0
406089,8a2e781c33ecb5ee4505d54d5fd1c5e8,None,苏州观智智能装饰工程有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

In [11]:
discovery_original.query('apno_cnt>31')[['entity_id','ans_id','company_name','apno_cnt']]

,entity_id,ans_id,company_name,apno_cnt
0,b62861edc99815f0000170071ffab65d,bc7e38df-d8cb-495a-bce6-b1a4d5de7107,DMW Corp.,253
9,048c766f0c1caa53d18e3ebb52a77132,1f989515-3747-44f1-ae79-934f34c80ff8,Output Technology Corp.,46
21,046e243b3e1f94e4d215b0f325c6375c,4f52f3d1-b3ce-4d3c-9371-acda838d2ca6,Juvora Ltd.,39
48,37b5011e0ca8cc80fffe51b17e710d88,54b6f568-8866-4ac2-be3e-b91db5e340f4,西安新华印务有限公司,37
65,34f3a71a11a1da74ef9094511902c99a,34858a73-f02d-44ad-ab67-1baa5ca761fc,重庆天戈陶瓷有限公司,49
...,...,...,...,...
2368251,57d7e6406477b9eeb4bb91ba0cd880d3,8a607b68-8c5b-49cc-995d-de1f59e3e8bd,"Hongfa Holdings U.S., Inc.",62
2368260,c4e26623a26752dffbe2e4cfa03dc974,bcb1e8bc-f820-4101-a7c0-70b18db4138a,上海拥立胶粘有限公司,147
2368283,43fcc5ff6b92f68a8bc1be6025614889,48929174-a4c0-4ad5-89d5-50a6230ad2da,佛山市南海特鑫瑞汽车装饰配件有限公司,48
2368313,3c0c777864ac90f494809b2c5a168177,1389950d-70bd-4344-a62c-cc0026fd7b00,扬州神驰新材料科技有限公司,55
2368319,a4cc033bfe6139f19d3d14ffb7336cf7,3b5a192c-f351-4a95-b001-f5d72206c705,靖江市达克罗涂覆工业有限公司,35

## joint_application_cnt

In [14]:
discovery_original.sort_values('joint_application_cnt',ascending=False)[['entity_id','ans_id','company_name','joint_application_cnt']]

,entity_id,ans_id,company_name,joint_application_cnt
55584,52693a47528072a668e62a1794044767,8d839b9f-81ba-4ee8-abf3-1576273cfdc2,国家电网有限公司,81142
1013744,2ca98d17ff6f2a9feff153bb5e9e330f,c5c21afe-99e8-482a-8a9a-1161e9fa6094,None,37274
2355302,c458715c35ae5bb0b601870a52edea48,c5c21afe-99e8-482a-8a9a-1161e9fa6094,中国石油化工股份有限公司,37274
420459,0a031381f7ef0c27f039a23c8c8e1769,7ef84e41-89ec-48df-a2d4-96023f38cd51,美的集团股份有限公司,36193
338240,e16b5c7888fa47c2efd2c7082065a665,41fb0d5e-b030-407f-ab1f-ee7c76195452,京东方科技集团股份有限公司,24842
...,...,...,...,...
818840,45216a923f8a81ba67acc515ac437878,8319dbe7-99bf-4048-ae22-889f2e7ae290,上海缀威新材料科技有限公司,0
818838,f77f120e243af41fc23c9149e0a3c3af,c505536e-ad77-47a2-8aae-fd1618a592b0,四川康而好动物药业有限公司,0
818837,e7e18facc77f56d12e6502459dcab89d,7f1305f4-054d-11ed-9940-323aa916fc88,北京中宝昆泰能源环境科技有限公司,0
818836,94c14f2a698f689739df6b9680a6d405,9a85baae-6673-4820-aa8b-7331ebf90020,广州沃克斯顿环境设备有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

In [16]:
alpha=3
seg_25=discovery_original[['joint_application_cnt']].quantile(0.25)
seg_75=discovery_original[['joint_application_cnt']].quantile(0.75)
up_limit=seg_75+(seg_75-seg_25)*alpha
low_limit=seg_25-(seg_75-seg_25)*alpha

In [18]:
low_limit

joint_application_cnt    0.0
dtype: float64

## tech_global_concentration

In [19]:
discovery_original.query('tech_global_concentration>0.0000598883113768807')[['entity_id','ans_id','company_name','tech_global_concentration']]

,entity_id,ans_id,company_name,tech_global_concentration
0,b62861edc99815f0000170071ffab65d,bc7e38df-d8cb-495a-bce6-b1a4d5de7107,DMW Corp.,0.000229
18,378d940d92f874a73b42316f76b99eb6,3eae3746-3bc6-430b-b7b0-4e605c2efa0e,Dura Cables Ltd.,0.000083
21,046e243b3e1f94e4d215b0f325c6375c,4f52f3d1-b3ce-4d3c-9371-acda838d2ca6,Juvora Ltd.,0.000156
51,81d92e9a5e1f506058df9dc30f560120,525853f5-ec4c-4381-b5ae-bd4c78ea6f93,龙口市复兴机械有限公司,0.000065
52,602a1577c4efe7f49a9177cb07ba5c46,b54e6587-3d11-4101-a09d-dcc112070107,"Micro-Clean, Inc.",0.000060
...,...,...,...,...
2368292,c426b1d91f469ed97fa20e4af523d4e7,0685e873-c389-407d-a9a8-990f80a3eef8,None,0.000069
2368311,b9004a1bd1f2689e4805ab42c165ac6d,f9a93ecf-dc33-467a-9882-8f363d7b1902,上海卓益得机器人有限公司,0.000224
2368314,56e1884b44760ad346bf78f9c51c0e2f,88c4658a-e43c-46c6-96c3-2d9e2e7261ca,无锡市赛能微电机有限公司,0.000072
2368315,6352d6f012f8a69035e0637547f0b30c,8246742d-0ec3-48c6-a8ef-a0587c655688,广州市誉路通机电设备有限公司,0.000157
2368317,d1dc7911f6e652f675e958ede1463573,948b44e8-6449-414b-9fc2-5cef9273f68b,绵阳市弘盛磁材设备有限公司,0.000086

## tech_width

In [21]:
discovery_original.sort_values('tech_width',ascending=False)[['entity_id','ans_id','company_name','tech_width']]

,entity_id,ans_id,company_name,tech_width
123333,6e6c118b15a409cb85772fb69d17bc65,6136f940-b5d7-4620-b09c-f92a2fff2fb4,Jianghan University,1504.0
1943863,a928bf4275c7d7085d11393d1c21f250,84ddb4c1-68ed-4eab-83d5-0ad6e1776c00,Kohler Co.,811.0
306928,45a8ba944975774f151ef055c4b98bf2,7a492294-2b70-4f46-80cd-cc2e3d1a76a8,None,754.5
1929745,5c6a88540ae4614d3b9236bad982419c,805be07e-7815-4397-a0ef-a6e4e9e44d23,Braun AG,608.0
2256382,b52a9e0c13616b398c712bdc1a663c37,b9542bfb-0726-4450-b20b-9a58fcd9fb7a,合肥京东方光电科技有限公司,592.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

In [20]:
discovery_original.query('tech_width>12.75')[['entity_id','ans_id','company_name','tech_width']]

,entity_id,ans_id,company_name,tech_width
30,7eb595cfaf582aa597acd9f2dc70b4c5,aff63c42-d5cb-4bd3-8e6a-24306d7d1e75,常州瑞点精密科技有限公司,14.0
59,d83de8062d5779a2ff7e1d75834f7228,d31c45e3-bd45-4983-bb89-a0b337a79a3a,PFP Industries LLC,16.0
106,dcb3c94691dae34e4da02388aee654ce,fd554c51-1638-484b-aee5-1ff2e81b27a8,和县绿源油脂有限公司,24.0
140,9ee480eb122546a92d8471c77e39d592,3fa39e6d-047f-4f73-b836-574e9a4e3b34,芜湖凯博环保科技股份有限公司,22.0
145,0201d4faae5dce03135387454dc11291,1280ed1a-dd9e-4e47-8a94-ab899fbc4de3,成都国铁电气设备有限公司,29.5
...,...,...,...,...
2368286,bfd438f0a68a797dddae198874676b72,ab5f7924-0cac-11ed-9940-323aa916fc88,广州弘海模具塑胶制品有限公司,13.0
2368291,f500d644d438696a57232b1fd78a690c,f11d7dbf-4711-4326-8e2c-9677e4f87520,江苏一尺宽信息科技有限公司,14.0
2368304,68ac8537422d484313e660bcb729e766,00b9a110-5c3b-4ce3-97c0-3b098ba1a0b6,常州市拓普新材料科技有限公司,15.0
2368313,3c0c777864ac90f494809b2c5a168177,1389950d-70bd-4344-a62c-cc0026fd7b00,扬州神驰新材料科技有限公司,42.0
2368319,a4cc033bfe6139f19d3d14ffb7336cf7,3b5a192c-f351-4a95-b001-f5d72206c705,靖江市达克罗涂覆工业有限公司,13.0

## joint_applicant_cnt

In [30]:
discovery_original.sort_values('joint_applicant_cnt',ascending=False)[['entity_id','ans_id','company_name','joint_applicant_cnt']]

,entity_id,ans_id,company_name,joint_applicant_cnt
55584,52693a47528072a668e62a1794044767,8d839b9f-81ba-4ee8-abf3-1576273cfdc2,国家电网有限公司,3822
132452,27661012a6fa15b31e7f43efdd1583f5,7f8bed13-1d3a-49c6-adaa-ed97e992793c,Tsinghua University,1433
2323133,3a5d102cd4f787427e585c99a4082145,825ac579-7117-4197-894a-4c288287fb7d,Toyota Motor Corp.,1238
490639,131e3f3a131950d26dd2beddf0eff303,a2727864-181b-4068-a5f7-1ad8e4684b6f,Advanced Industrial Science & Technology,1221
817786,d829b2a370d8bf2ee8cc5dc7b6e9d862,82e90a94-6424-4b39-8c1a-cca341427ac0,Zhejiang University School of Medicine,1095
...,...,...,...,...
818840,45216a923f8a81ba67acc515ac437878,8319dbe7-99bf-4048-ae22-889f2e7ae290,上海缀威新材料科技有限公司,0
818838,f77f120e243af41fc23c9149e0a3c3af,c505536e-ad77-47a2-8aae-fd1618a592b0,四川康而好动物药业有限公司,0
818837,e7e18facc77f56d12e6502459dcab89d,7f1305f4-054d-11ed-9940-323aa916fc88,北京中宝昆泰能源环境科技有限公司,0
818836,94c14f2a698f689739df6b9680a6d405,9a85baae-6673-4820-aa8b-7331ebf90020,广州沃克斯顿环境设备有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## top5_current_impact_index

In [31]:
discovery_original.sort_values('top5_current_impact_index',ascending=False)[['entity_id','ans_id','company_name','top5_current_impact_index']]

,entity_id,ans_id,company_name,top5_current_impact_index
663806,42cfe433aa9df65611224532372bfa56,3249b2cf-1178-42cd-82c3-4c5a0865dbd5,Laboratorios Miret SA,196.393154
28912,88ba8182a00a42734fb35034595fac3d,1de7d5f6-dd74-4229-b0b2-faf729b244f2,Arnold Oil Co. of Austin LP,180.809397
1029997,62e98285dac21a71e6b5c582a8ec69ac,43f40691-7c8c-42a2-825a-73c3aee7cee0,"PhishCloud, Inc.",177.895243
430920,0c4bc9c562d44e20236af134f6e71c63,5f4355fc-4650-4dd8-a790-ad0878a077f6,Wagner GmbH & Co. KG,154.393517
1672318,bc0ee46e77ab937e0f41ad9c198ee7ab,4b357f73-2d73-4d03-b27e-eb9575a1efc8,American Energy Innovations LLC,135.356754
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## most_cited_patents_value

In [33]:
discovery_original.query('most_cited_patents_value>763600')[['entity_id','ans_id','company_name','most_cited_patents_value']]

,entity_id,ans_id,company_name,most_cited_patents_value
61,70dea95103d764e10b06e885759fdfdb,973c815a-279d-493a-a408-f5d186003144,None,768100.0
145,0201d4faae5dce03135387454dc11291,1280ed1a-dd9e-4e47-8a94-ab899fbc4de3,成都国铁电气设备有限公司,2385200.0
183,4c6b5bcdf5c6c229d03833e8d01cb4bc,49d3a512-32d4-4cb7-9b8d-a6a01b041262,Oxycom Beheer BV,14489050.0
217,d50375d58a1dba2871e77c0648238529,e99afb88-af81-4b52-8b9f-5a4352c16e21,"Hugle Electronics, Inc.",4703300.0
224,ac4ca75d93bb3c276309c00b5d8b14d7,fa07345f-066b-463a-8f0a-67d4056e1789,"Adagene, Inc.",1205500.0
...,...,...,...,...
2368200,d582395a9a054fa598c3e70feb5e6997,0457f509-8d8d-463d-ad6f-958d99abb39d,广州邦讯信息系统有限公司,1315150.0
2368236,075588946cdd8182850807271e2b050d,a0724050-d481-4f42-bf64-aa1e932f14a4,广州市振宇拉链机械有限公司,992900.0
2368250,6fc797c8e8c8b5138255e2b2c5364535,7e33ceed-5c39-478e-876d-b6c3c9e6b66f,宁波勋辉电器有限公司,837400.0
2368251,57d7e6406477b9eeb4bb91ba0cd880d3,8a607b68-8c5b-49cc-995d-de1f59e3e8bd,"Hongfa Holdings U.S., Inc.",25527650.0
2368311,b9004a1bd1f2689e4805ab42c165ac6d,f9a93ecf-dc33-467a-9882-8f363d7b1902,上海卓益得机器人有限公司,1048400.0

In [34]:
discovery_original.sort_values('most_cited_patents_value',ascending=False)[['entity_id','ans_id','company_name','most_cited_patents_value']]

,entity_id,ans_id,company_name,most_cited_patents_value
39371,53a52d8ed4953963b8bb4dad66ce8d21,59b69902-ee5a-4a48-bab2-5c2a1f0b64a8,"ZeniMax Media, Inc.",138678250.0
1499858,cd0c2d4e7e313fe7ade2a4379a21f028,5ab64ec8-b354-4e56-8d29-276127318aed,Evoqua Water Technologies Pte Ltd.,130649950.0
1700489,fcd06cbde08c32e4d3de1024c997492d,571e2188-e0f0-4588-9572-3cf9252bdb86,"Sunrise Micro Devices, Inc.",127523500.0
673865,ffc1a1f2a3cbaf6011838159ef8d7a9d,fc27aff6-f783-4c3b-b36b-82c6b26b923e,Aurora Labs Ltd. (Israel),127514750.0
1974279,4e5526052bb10f5d7261e406d5e5a0e0,45e56aaa-d051-11ec-a8d6-fe339923daad,Coronado Aesthetics LLC,125203300.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## external_licensing_cnt

In [35]:
discovery_original.sort_values('external_licensing_cnt',ascending=False)[['entity_id','ans_id','company_name','external_licensing_cnt']]

,entity_id,ans_id,company_name,external_licensing_cnt
1082934,e09a2e6b1cde06dcf537ac961fb4ec36,7f78b0e8-64b7-4fb7-89b9-1c1caab54d7b,深圳迈瑞生物医疗电子股份有限公司,1169
1205477,93bff0a8a2a2977d55c3f0f07329acee,0238db74-1f08-47a1-99c8-2d899de7051c,Nanjing Forestry University,1120
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,713
1847829,bb8a637c3e058e6497dfd3467255811f,6b782ed4-46e3-423c-97d5-e8fd98ef2908,Lawrence Livermore National Laboratory,662
1066602,5d64a328605688c0b84b8969ac056665,7c7000d5-b6f8-4883-b83d-d9716d7a2be5,None,647
...,...,...,...,...
790784,5d890cc194ba6868fe5c2e167b32d966,44503f94-51b9-45b1-ac8e-3b3cc5d15c16,云南炬鑫康利科技服务有限公司,0
790785,5e9f4dfb0cd541b383f14718af4c0aca,482396c0-fc66-11ec-b21e-5251e459860d,深圳市旭俊科技有限公司,0
790786,59413e5a44a1a647a4ccf42ac42f42f2,None,济南卓软信息技术有限公司,0
790787,b3f1761856b40b85e28c76941b35af04,dccc75fe-8fd4-41c1-9fab-949ba4ae550a,None,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## core_patents_cited_by_cnt

In [36]:
discovery_original.sort_values('core_patents_cited_by_cnt',ascending=False)[['entity_id','ans_id','company_name','core_patents_cited_by_cnt']]

,entity_id,ans_id,company_name,core_patents_cited_by_cnt
1042958,736daa01387a3aa509a4c48fbcf19dd7,1f8b0a60-9b7a-4bfa-8831-ad57a7ccec69,"DexCom, Inc.",28658
1350273,f47f3d325e904871784a30865a7ef7e4,961f8655-c0ae-45d8-9d63-b7ab6b3494c6,Cilag GmbH International,24284
1536575,74fcb42b5d94eadb060ca051ea241d49,7d0a9047-c0b3-4871-a6bf-db9af1797eac,"Ethicon Endo-Surgery, Inc.",20025
339405,ab30a4f3f10e812ee73da1bdda5567f3,313732cf-a16b-42ed-822e-d14a47e65ba1,Japan Science & Technology Agency,16175
269897,a2f7be6c27c14218c4d8500508a9f769,1c4ec851-f1ae-400c-9a1a-c464ee5ccb97,"Cercacor Laboratories, Inc.",15080
...,...,...,...,...
1221568,ace39ca550eac09ae6bf11e760df1ed3,b275a711-4ec9-44bb-bd12-16169635d801,天津万德伟业科技发展有限公司,0
1221567,6e73619af933fe9f3807aeec5fa4b0c8,4d7af25a-31e7-4d94-87d1-b8fafa3d7a58,临沂郑玄醉酒业有限公司,0
1221566,c22319eb821dc28277dda33aacc3c089,b52bdc7f-e4df-4b4c-8c25-3ada38da43cd,None,0
1221565,ff038d25774781628ee665cf28a07b15,None,成都聚乐游科技有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## core_patents_cited_by_ratio

In [37]:
discovery_original.sort_values('core_patents_cited_by_ratio',ascending=False)[['entity_id','ans_id','company_name','core_patents_cited_by_ratio']]

,entity_id,ans_id,company_name,core_patents_cited_by_ratio
757726,5922634b894922496fd55b7a8bae1934,2c8ffe46-1c26-11ed-9c08-76f2c33733ed,Hybrid Tech LLC,2038.000000
2124533,0442e4c0629768daafd904b2c9ffb44f,5eea958c-7f63-11ec-bb99-aa1cc5da68a3,Webroot Software Inc.,1272.000000
1513832,e5e7a074358865cac65f03a4f93d351a,9e905d03-ca05-4b5e-bdc4-640f31f1fd5f,Gyrus Group Ltd.,1144.666667
1350273,f47f3d325e904871784a30865a7ef7e4,961f8655-c0ae-45d8-9d63-b7ab6b3494c6,Cilag GmbH International,1055.826087
838138,d95332991f58feb8fcdf63b965452e0f,5f497007-b812-4248-b7bc-127981b630bb,VPR Brands LP,1037.000000
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## avg_cited_by_cnt

In [38]:
discovery_original.sort_values('avg_cited_by_cnt',ascending=False)[['entity_id','ans_id','company_name','avg_cited_by_cnt']]

,entity_id,ans_id,company_name,avg_cited_by_cnt
1097652,6b66af21b53fd8268833b433fb25b323,20ea3324-2464-4bb5-a1e5-21a29bdbb6fb,"Future Labs, Inc.",2166.0
191728,0d90faf7753f70cb84383cc21a86f1c8,d670d049-2084-4b84-ada2-424124835b35,LBS Innovations LLC,2141.0
1378436,dfebf67ca2d4310d7dfbab2b8ec1a26d,70ae77aa-8f74-4699-acb2-606bbc94b232,"PJC Logistics, LLC",2102.0
1258093,3ff7513af00da9fe4d481d0dacb2afb2,f11d092f-86f1-41bb-8c0f-a60ae5e312e5,Christian Neuber,2060.0
1953140,d5cf22cf0142c0023677ad1f0f7eebfe,dff28503-b3f7-4d07-91ed-2a4f6dbd82f5,State Street Global Advisors Funds Distributor...,2000.0
...,...,...,...,...
803372,e905cc64e8d94407a0f3c10b03d39e0d,8ab07941-6abf-4024-bab7-8762ac1363d8,Meto-Fer Automation AG,0.0
803371,9207af792695b3642dea0905d09519e6,196af06b-4f35-4d2a-822e-07dcc12c419a,慕己（上海）珠宝有限公司,0.0
803369,c24c9680bfb4361805056391d6c07959,85cd7535-173e-4c97-95b0-3eb90ee7c780,天津市兴丽电器设备有限公司,0.0
1619662,597401c3a1563bc99718186471d940fe,None,苏州市鸿修市政景观工程有限公司,0.0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0.0

## value_sum

In [40]:
discovery_original.sort_values('value_sum',ascending=False)[['entity_id','ans_id','company_name','value_sum']]

,entity_id,ans_id,company_name,value_sum
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",3.995119e+10
1481377,af85ee378b02ba0dc91ce645e7032f51,88160f04-ce97-4e32-ae41-e7ad897aaa17,"QUALCOMM, Inc.",2.975023e+10
2323133,3a5d102cd4f787427e585c99a4082145,825ac579-7117-4197-894a-4c288287fb7d,Toyota Motor Corp.,2.230705e+10
1861299,4ccadf73adf70c9bdd1a4205e74c125e,4c2a691c-0636-4a1b-a8ca-909e0b517647,"Canon, Inc.",1.978356e+10
846595,5c599187502fb45c7ad46fa69b436037,dd4aad8f-398b-4a0d-822d-9d2f5123448e,"LG Electronics, Inc.",1.962107e+10
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

##  value_top5_avg

In [41]:
discovery_original.sort_values('value_top5_avg',ascending=False)[['entity_id','ans_id','company_name','value_top5_avg']]

,entity_id,ans_id,company_name,value_top5_avg
1481377,af85ee378b02ba0dc91ce645e7032f51,88160f04-ce97-4e32-ae41-e7ad897aaa17,"QUALCOMM, Inc.",15330000.0
1169671,56f905e632e18c87e0afe588e2c1f34a,5b70b986-d645-4ae3-80bf-ebba45b0bf99,"Apple, Inc.",15324000.0
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",15034000.0
1687403,54267fe0f7e60d80919c0d45c1174ed7,ff5dc7a8-eeb8-42d7-ac66-d1bfbc9d86c2,Intel IP Corp.,14992000.0
2213045,a1b3c153ef4078d993ba38c2f1d414e2,d5f7d905-fc83-4315-892f-482005bfbb5a,Sony Group Corp.,14784000.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## avg_remaining_life_span

In [42]:
discovery_original.sort_values('avg_remaining_life_span',ascending=False)[['entity_id','ans_id','company_name','avg_remaining_life_span']]

,entity_id,ans_id,company_name,avg_remaining_life_span
1351291,e4733aa6ddd1ef138be43ba341c74c4d,5c83dd31-38f5-4db2-b979-055b5ca4af08,Matrix International Ltd.,24.986301
2074568,7181f80fedf2a597e2ac0fef0abcee07,99bf3a84-557b-11ed-801d-aeccd77a817c,Boostmarket Ltd.,24.983562
1011817,c55e07c9b795155d7e3338e578102b65,fce675e6-48e3-11ec-a2d3-16d47aa0b287,"Aescape, Inc.",24.980822
983420,37d6a9d793a4178705cf9adb232a9ac8,e1c2c228-53fb-11ed-8c7b-ca0d804f5905,GDP Koral sro,24.978082
1330243,4b827a29a95d863de3735d56d912144e,aaff1ec0-eb90-440b-8461-5cc7869c8eab,Silver Cross Ltd.,24.975342
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## avg_technology_score

In [43]:
discovery_original.sort_values('avg_technology_score',ascending=False)[['entity_id','ans_id','company_name','avg_technology_score']]

,entity_id,ans_id,company_name,avg_technology_score
1816961,12b4bd54c5e30e18d666abee4e6eeae1,2a52b4a0-cc57-41e0-b709-f6607d2f0912,河南省聚友塑料有限公司,0.9507
1038259,3e7649aedcbe42d5fcd09d6f5eca28bb,476c7a64-8c66-42ed-b424-e2957640bdd1,灌南县金凯包装有限公司,0.9494
1386008,5685549f8bf0d9e688fd9adbb375b41a,a42f5178-77ab-44ae-a662-d551f658509f,哈尔滨市都邦节能科技有限公司,0.9483
1658230,2f9b465d80f71d0d7240266f50318399,5abaf8fa-31cb-4c54-a843-1bd39db3bd81,金华造物新材料有限公司,0.9478
354637,192242af48b3c30ff92b2f36e100a21f,36a028dc-77a0-40a6-989c-e88e75676f3f,深圳市金无曼工业新材料有限公司,0.9477
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

##  value_avg

In [44]:
discovery_original.sort_values('value_avg',ascending=False)[['entity_id','ans_id','company_name','value_avg']]

,entity_id,ans_id,company_name,value_avg
70735,bfe163a21f55b38962dc35c46396c78a,382fb0ab-a109-4aae-964b-a4c4a4fe7c90,Sun Patent Trust,13230000.0
2189771,b2a52dbc5710b6457180404272d20815,1e781290-2932-406c-af5d-1ad97c8ed2f3,"Dalton Chemical Laboratories, Inc.",12280000.0
1798757,581c838a3aab69a9dad9bcecdeded97d,307c1ea2-611e-401a-aa3d-e90fa2926e8c,"Mobeewave, Inc.",12170000.0
757726,5922634b894922496fd55b7a8bae1934,2c8ffe46-1c26-11ed-9c08-76f2c33733ed,Hybrid Tech LLC,12080000.0
553197,527683f87c5a92282e0f25f2456f83d1,ce5c6fef-ed73-4d2c-b042-20ae4e8dfaa1,"Kinetic Concepts, Inc.",12080000.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## in_examing_ratio

In [45]:
discovery_original.sort_values('in_examing_ratio',ascending=False)[['entity_id','ans_id','company_name','in_examing_ratio']]

,entity_id,ans_id,company_name,in_examing_ratio
1186243,e68217b8c16dd70e94c090696be597c6,68edcf2b-9762-453c-a2f6-e4154b107caa,句容市杨修林果园,1.0
1775588,cc564d60efc67c269be489d188e82d24,73bcc13a-4bad-11ed-801d-aeccd77a817c,郑州醉旅超硬材料有限公司,1.0
1905499,2f3c7039a2f92181c669140b9558a1ad,fee112d2-0555-11ed-9940-323aa916fc88,深圳市华置科技有限公司,1.0
663895,820d3ddb93001a2475f10b7dbedafafc,660fc9cc-7c81-4ad3-a2b2-39c591c26977,赣州骏虔生物科技有限公司,1.0
77144,0214d67b5c9984011d48d0d81ba198cb,967a2ad2-2867-11ed-952a-4267ea7eeb11,None,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## granted_invention_ratio

In [46]:
discovery_original.sort_values('granted_invention_ratio',ascending=False)[['entity_id','ans_id','company_name','granted_invention_ratio']]

,entity_id,ans_id,company_name,granted_invention_ratio
1293693,dc4dcbb1cf9be03bee898018841f73e2,0dc1aed0-65b6-4756-a804-d64e6a782ad0,芯无线（北京）通信技术有限公司,1.0
752925,cc47ee6ec63deb2509224d0a796c0e0b,af81ace4-88b7-11ec-bb99-aa1cc5da68a3,深圳市易思博酷客科技有限公司,1.0
1690687,511ac55712c07a01ec1e0c2310c83558,88d6968d-c165-4b68-a12b-db21b108b3f6,上海羧菲生物医药科技有限公司,1.0
1690681,4c530cdbb3caa49bd8dc875d28eb508b,8bdf2362-bbd6-4571-b2b1-2f473d7df90c,泉州安盛船务有限公司,1.0
1045645,2a02740bdb6040bef5277691c99da758,267d52bc-2433-4d3f-a226-683db57c3a96,南昌通源实业有限公司,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## granted_invention_cnt

In [47]:
discovery_original.sort_values('granted_invention_cnt',ascending=False)[['entity_id','ans_id','company_name','granted_invention_cnt']]

,entity_id,ans_id,company_name,granted_invention_cnt
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",155627
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,100934
2323133,3a5d102cd4f787427e585c99a4082145,825ac579-7117-4197-894a-4c288287fb7d,Toyota Motor Corp.,92244
1861299,4ccadf73adf70c9bdd1a4205e74c125e,4c2a691c-0636-4a1b-a8ca-909e0b517647,"Canon, Inc.",88794
1481377,af85ee378b02ba0dc91ce645e7032f51,88160f04-ce97-4e32-ae41-e7ad897aaa17,"QUALCOMM, Inc.",88028
...,...,...,...,...
1136509,492c2d1adc00c55f4a78fbf6655fc1d8,c8c37f15-ca41-44cd-84cc-13560f7bc1c7,Robotise GmbH,0
1136508,d4ba46b91fd3f30305742f476357463e,5c8be24e-784c-44ed-bd53-6f5f11ca516b,MLT Aikins LLP,0
1136507,37d91469a714f77a1dbcc4fda663ee1f,0562842a-2daf-45e6-ba03-9c235029efeb,深圳市蓝天计算机技术有限公司,0
1136506,144e5e78bffb98e97418e7dfde875f3b,bca79823-53bd-4a1a-b0b6-26a9af4b287d,None,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## invention_ratio

In [48]:
discovery_original.sort_values('invention_ratio',ascending=False)[['entity_id','ans_id','company_name','invention_ratio']]

,entity_id,ans_id,company_name,invention_ratio
1456884,7ca5ce4095f271f8f22f66680fc42855,3a7fee2d-b872-43d1-a011-3177cf357c1c,Toyo Kiki Kogyo Co. Ltd.,1.0
951695,2d0544d4852d0554cb8ab3f7d06e2483,edb0f499-c107-46b2-88fd-ae1437d9112e,"HEPCO, Inc.",1.0
440916,52b2c6b4b28a9947eaf75b9e9de407c4,5ed01303-5681-4e1b-9d91-5e96a26ca32c,广州远志资讯科技开发有限公司,1.0
1772673,b7ec1dc09082e423ba0b0c604f1ae846,08f5bf7c-6872-46a6-98bb-995181c2844b,天津市源泉恒泰机电设备有限公司,1.0
951682,2d2185f273cc892b8f1f9e1a94092c57,a2a24089-74d4-4c7f-89b6-18e11cd40aae,潍坊丁零电子科技有限公司,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## ip_dependency

In [49]:
discovery_original.sort_values('ip_dependency',ascending=False)[['entity_id','ans_id','company_name','ip_dependency']]

,entity_id,ans_id,company_name,ip_dependency
2165919,52d250b7d4de6212cf2ddb171a8db4c4,2b7da462-05c0-4bf7-af4c-36e81360eaac,None,1.0
1966309,e1c3ce42b40e1586d150e14dc687b8aa,56b36e6b-288a-4c35-b654-9f2db09bcf12,"Tianbai Broadband Net Tech (Beijing)Co.,Ltd.",1.0
413095,2cf2f64c1635f0314b767d38c4874770,0a19e301-067a-44c7-8b0d-5763830aa6be,None,1.0
1644793,7e85efa2861478f34ab67801e9cf3ed3,491d32cf-e86f-43cf-97c6-b7df133c1e6c,Hefei Taigeke Regeneration Energy Develop Co. ...,1.0
1553699,83614acce41f3bcf553a630b8d4ec002,e8b15025-dc06-4281-8c0d-ae0f0e392d11,河北金智博文化旅游发展有限公司,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## total_patent_award_score

In [54]:
discovery_original.sort_values('total_patent_award_score',ascending=False)[['entity_id','ans_id','company_name','total_patent_award_score']]

,entity_id,ans_id,company_name,total_patent_award_score
55584,52693a47528072a668e62a1794044767,8d839b9f-81ba-4ee8-abf3-1576273cfdc2,国家电网有限公司,976
1013744,2ca98d17ff6f2a9feff153bb5e9e330f,c5c21afe-99e8-482a-8a9a-1161e9fa6094,None,822
2355302,c458715c35ae5bb0b601870a52edea48,c5c21afe-99e8-482a-8a9a-1161e9fa6094,中国石油化工股份有限公司,822
132452,27661012a6fa15b31e7f43efdd1583f5,7f8bed13-1d3a-49c6-adaa-ed97e992793c,Tsinghua University,818
549787,205ab48beb9a464cc803f771e8e70791,d52c4923-cc0d-490c-bed4-5e2bc8afa127,珠海格力电器股份有限公司,595
...,...,...,...,...
790419,1cd9bfc9dd98238e1524573ee0eb12ce,e1bccc61-bf11-4368-b72f-dd8f1ebff46f,浙江佰鸣信息科技有限公司,0
790420,17327ea633725feb09fdb030ab4850f8,22fbbe21-c89f-4919-8cc6-173b57aae33a,长葛市赛丹机械制造有限公司,0
790421,0137a39395a3d3d2491001ee3a9baec3,d5f827d3-87c5-42f6-ad3e-2d6e093a0cef,台州萨普三维科技股份有限公司,0
790422,6e79827c66878b266a50c16d3129814c,2d184bb6-f516-4720-a632-4243e6633f53,天津市众隆科技有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## patent_valid_ratio

In [55]:
discovery_original.sort_values('patent_valid_ratio',ascending=False)[['entity_id','ans_id','company_name','patent_valid_ratio']]

,entity_id,ans_id,company_name,patent_valid_ratio
1184286,f55d3217951a69276db49e302d7f07ba,6a6a95c8-7444-4072-941d-116d7b48bef6,中塑（涿州）包装制品有限公司,1.0
815226,cc288ead8e47fde3586ea852e858081f,a83bd664-4ca6-11ec-8da2-921dbd374d12,台州市路桥聚鑫电子有限公司,1.0
1769779,86be0e30ec0e2cf4cf92bc9437fa29a1,b5183a3b-7fd2-45dd-b363-55868f3d11c8,安徽骏美设备有限公司,1.0
1769774,72d55501db0b7eaa0e526eaf86edd577,b31aec98-050d-42ad-9ebc-99b79ac67bcd,惠生新材料研究院（深圳）有限公司,1.0
815486,d9b42114e528207cd98e9ddbda6b56fa,c9fe3433-c5fb-456d-b3b2-a3cdc3b0ffdf,山东省菏泽市佳钥电子科技有限公司,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## avg_3y_cnt

In [56]:
discovery_original.sort_values('avg_3y_cnt',ascending=False)[['entity_id','ans_id','company_name','avg_3y_cnt']]

,entity_id,ans_id,company_name,avg_3y_cnt
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",26517.666667
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,24388.333333
846595,5c599187502fb45c7ad46fa69b436037,dd4aad8f-398b-4a0d-822d-9d2f5123448e,"LG Electronics, Inc.",15806.666667
1481377,af85ee378b02ba0dc91ce645e7032f51,88160f04-ce97-4e32-ae41-e7ad897aaa17,"QUALCOMM, Inc.",15161.000000
549787,205ab48beb9a464cc803f771e8e70791,d52c4923-cc0d-490c-bed4-5e2bc8afa127,珠海格力电器股份有限公司,15055.333333
...,...,...,...,...
980608,509ddf7f3636cc9f22220320bd9e073d,None,陕西飓祥实业有限公司,0.000000
980607,1068777ae0a086f71d21da643355f5b9,4dd76a16-4109-4fc7-a6be-41a91d4a19de,"Pike Machine Products, Inc.",0.000000
980606,11b05ea5f487f5a434f3fdfde46d1e0a,0608800b-54a5-4ab3-89d1-995f1559b000,"Papivax Biotech, Inc.",0.000000
980604,ce9654269652865577ec15434790eaf7,54cb391e-f3ae-4691-9317-d038f6809232,Omote Tekkosho KK,0.000000
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0.000000

## patenting_growth_ratio

In [57]:
discovery_original.sort_values('patenting_growth_ratio',ascending=False)[['entity_id','ans_id','company_name','patenting_growth_ratio']]

,entity_id,ans_id,company_name,patenting_growth_ratio
2037174,c5a76b31a052e30bae1613f804f64558,1192c4f2-96ae-43a4-b895-d31d62a81636,Industria Briantea Ferramenta Minuterie Di Fum...,999.0
1099169,6bb8f3b7b9c057c67a1ece3767d5643c,26a35b71-9492-44ab-bf15-8dc563a49638,苏州锦园旅游用品有限公司,999.0
1099182,3bcfcc9a56596f96c67cb772cc362a99,59ee2748-72e7-4372-9d35-5ee2167de2ec,None,999.0
1099180,900a113a2b7a3c827dfb18d930edc24d,315cb71e-84e8-11ec-bb99-aa1cc5da68a3,"PROTILLION BIOSCIENCES, INC.",999.0
604863,4484c9d227b5b68248c32c792473d0c4,ec6be561-88b3-4a97-99e4-8e92abda4e00,Profalux Industrie SAS,999.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## self_cited_by_ratio

In [58]:
discovery_original.sort_values('self_cited_by_ratio',ascending=False)[['entity_id','ans_id','company_name','self_cited_by_ratio']]

,entity_id,ans_id,company_name,self_cited_by_ratio
150677,a9a99e8caa87a597a08d27a91b27b482,08b04c68-560d-4093-92dc-7614b666334e,Mars Air Systems LLC,1.0
1166123,2c50e285e9109fbd3826f7a941e8d4ac,9feaa7e4-86b6-423e-b4f9-7456e9619fc9,Dongguan Unirise Electric Wire & Cable Co. Ltd.,1.0
522231,a2524dee8e9068aa1966b5e0d71d54d3,cd08370b-b42e-44c3-b78f-d059a80d154c,"EIS Electronic Integrated Systems, Inc.",1.0
1280690,c7626c72d93e1c6a8a21d637f07d5b94,36db8c64-3fce-42db-b9b2-2e3906959d8d,Nutrisher Ltd.,1.0
1122304,3611df2bf6dcf974fd606b8aee121129,99710c3b-5109-40a4-bf6d-4ef17914b809,天津市世一精密塑胶有限公司,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## invention_stability

In [59]:
discovery_original.sort_values('invention_stability',ascending=False)[['entity_id','ans_id','company_name','invention_stability']]

,entity_id,ans_id,company_name,invention_stability
2275660,46b0b867cfc33d45cde6bc22e2c1fdfe,50a3383a-0e1c-41ab-a747-bba006345d3f,"Matsushita Sangyo Co., Ltd.",5564.756283
1018949,35820d86eb1649b7dc08a730a1a6ee29,456c9715-18cf-4976-89c5-157260aa63e2,OPPO广东移动通信有限公司,5146.111153
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,3951.720032
681474,ede65ac41de63dce995c798743a2abc3,20cc3230-7ccd-4bac-b8cd-616e525b5c86,Panasonic Intellectual Property Management Co....,3512.768576
2334049,e16094dcb62483c7713bad0a79c31c5b,dadb8b6f-6e98-48d7-b495-f1478564958b,None,3494.378191
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## non_design_apno_cnt

In [60]:
discovery_original.sort_values('non_design_apno_cnt',ascending=False)[['entity_id','ans_id','company_name','non_design_apno_cnt']]

,entity_id,ans_id,company_name,non_design_apno_cnt
2275660,46b0b867cfc33d45cde6bc22e2c1fdfe,50a3383a-0e1c-41ab-a747-bba006345d3f,"Matsushita Sangyo Co., Ltd.",788177
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",634790
2334049,e16094dcb62483c7713bad0a79c31c5b,dadb8b6f-6e98-48d7-b495-f1478564958b,None,564521
1861299,4ccadf73adf70c9bdd1a4205e74c125e,4c2a691c-0636-4a1b-a8ca-909e0b517647,"Canon, Inc.",539901
578572,0e0e87c1511d46c5f7396532dea64e34,7961ed12-1f56-4967-a032-023d2f43d359,Hitachi Ltd.,513250
...,...,...,...,...
408609,d29ae2fd644c584889928d7aa6c86357,None,烟台青农禾农业科技有限公司,0
1573350,7386e1b4b315715c714fb69f1352cbe3,6e22aba8-3038-11ed-952a-4267ea7eeb11,哈尔滨沃兰迪体育用品有限公司,0
408607,e42585756af838c67c1770a0a84f8130,e57b6b3a-4b2d-4243-8c7c-078de88627e7,Pro-Pac Group Pty Ltd.,0
1573358,963e094a02f024545007ca2fc9f66e24,c36abb92-2301-465f-a41e-3dc0dd1e7fe9,徐州一碗绿食品有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## active_inventor_ratio

In [61]:
discovery_original.sort_values('active_inventor_ratio',ascending=False)[['entity_id','ans_id','company_name','active_inventor_ratio']]

,entity_id,ans_id,company_name,active_inventor_ratio
181451,b5b3c079910ec6928a11b1198bef6a0e,d6ea4d3b-c9cc-443e-957a-8df12b4570d1,广州市亚强电子科技有限公司,1.0
625849,d1321bcb7e70b5c8cac54e45f3aab00a,e9237d50-1412-4052-8903-4a8cc3582097,宁波克林斯曼智能科技有限公司,1.0
1106746,e5cac049f6f749c71834fe40461e9cd8,8cbb0189-86ab-4555-893e-127032879211,广东聚腾环保设备有限公司,1.0
2265397,f586299eb0f2ebb33280dd966ecafa14,b461ce40-ecc2-496a-a281-6964d2634aa3,广州耐雪制冷设备有限公司,1.0
526650,9efc766ef11ef60e40fdbedf6a5b00a6,77e916e5-10e6-46f4-99ea-21319131fe40,宁波振锐智能机器科技有限公司,1.0
...,...,...,...,...
2368316,15574294baf96d7ae070918b9186ad16,None,烟台园城黄金股份有限公司,NaN
2368318,fc7c64949cc2fb7d7e9b5132b25688e4,None,甘肃股权交易中心股份有限公司,NaN
2368320,d63bc5dd173e863072266b122d840658,None,上海学点教育科技有限公司,NaN
2368321,f289411ee29c955b5bea381ef712e1ee,None,上海奉光园林绿化有限公司,NaN
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,NaN

## granted_invention_cnt_pb_1y

In [62]:
discovery_original.sort_values('granted_invention_cnt_pb_1y',ascending=False)[['entity_id','ans_id','company_name','granted_invention_cnt_pb_1y']]

,entity_id,ans_id,company_name,granted_invention_cnt_pb_1y
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",19375
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,14331
2323133,3a5d102cd4f787427e585c99a4082145,825ac579-7117-4197-894a-4c288287fb7d,Toyota Motor Corp.,10572
846595,5c599187502fb45c7ad46fa69b436037,dd4aad8f-398b-4a0d-822d-9d2f5123448e,"LG Electronics, Inc.",8833
1861299,4ccadf73adf70c9bdd1a4205e74c125e,4c2a691c-0636-4a1b-a8ca-909e0b517647,"Canon, Inc.",8478
...,...,...,...,...
921912,df68f7a454674db541060f8e1a17112a,None,北京随考通科技有限公司,0
921911,2034bb78ca543d2205146ede1be017ee,1c760a84-dead-4074-8c74-be5c813963ce,Daehan Gm Corp.,0
921910,7b719ea2db0958c6c3b41c835c316f1d,e05e481b-96d6-4199-9da9-6334bf3e9710,东莞市优诺美健康科技有限公司,0
921909,67df747faad4ad5503861af96030d17f,50138cad-a341-4151-b25a-c77239c168db,湖州杭佳弹簧有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## granted_invention_cnt_pb_original_2y

In [63]:
discovery_original.sort_values('granted_invention_cnt_pb_original_2y',ascending=False)[['entity_id','ans_id','company_name','granted_invention_cnt_pb_original_2y']]

,entity_id,ans_id,company_name,granted_invention_cnt_pb_original_2y
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",38808
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,30338
2323133,3a5d102cd4f787427e585c99a4082145,825ac579-7117-4197-894a-4c288287fb7d,Toyota Motor Corp.,19257
846595,5c599187502fb45c7ad46fa69b436037,dd4aad8f-398b-4a0d-822d-9d2f5123448e,"LG Electronics, Inc.",18890
1481377,af85ee378b02ba0dc91ce645e7032f51,88160f04-ce97-4e32-ae41-e7ad897aaa17,"QUALCOMM, Inc.",17660
...,...,...,...,...
831686,c71ca0546333df243e2b0189f2bdfa28,598a7431-a2d3-4618-b9b5-62942eb598a6,佛山市晟茂金属建材有限公司,0
831685,78e4a9ad7e94f2abd6f0c051fc6c73e6,cab61882-1d84-472a-a01a-2c08c748e189,郑州精诚耐材科技有限公司,0
831684,43e78e1ceb839d4ec7d7a9f96c5643b9,efbe9092-6e7e-424c-b1dd-5c7d403f7839,苏州市慧视通讯科技有限公司,0
831683,6bedb62f4a54e208136947ea63f95cfc,696cd104-9cdb-4cde-ae24-cb7dc4615126,广州丰颐美容仪器有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## apno_cnt_valid_5y

In [64]:
discovery_original.sort_values('apno_cnt_valid_5y',ascending=False)[['entity_id','ans_id','company_name','apno_cnt_valid_5y']]

,entity_id,ans_id,company_name,apno_cnt_valid_5y
343099,08324673176ff8c6b97f1d4b0313fb7d,d4ac1a8d-2ce6-4238-93ad-738cbe3b46c8,"Samsung Electronics Co., Ltd.",98794
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,82982
55584,52693a47528072a668e62a1794044767,8d839b9f-81ba-4ee8-abf3-1576273cfdc2,国家电网有限公司,58400
549787,205ab48beb9a464cc803f771e8e70791,d52c4923-cc0d-490c-bed4-5e2bc8afa127,珠海格力电器股份有限公司,55559
846595,5c599187502fb45c7ad46fa69b436037,dd4aad8f-398b-4a0d-822d-9d2f5123448e,"LG Electronics, Inc.",54104
...,...,...,...,...
302863,0c13332e082ca7c1398935a161983568,None,纳思达科技（大连）有限公司,0
1249698,46dbc1b48b0573d38ef0ab9a1adfa18a,None,武汉半谷医疗技术有限公司,0
302865,9a9b322094e7fde234178373a06907f2,5cc29d84-2722-4fc5-bd53-2ef3fd68f01c,None,0
1249693,c212a1552a2c24b4719eb1fbbf487fd8,dbc6cf53-56d2-44fe-8d82-35ce91e0b999,惠州市名商高科实业有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0

## non_design_pct_apno_cnt

In [65]:
discovery_original.sort_values('non_design_pct_apno_cnt',ascending=False)[['entity_id','ans_id','company_name','non_design_pct_apno_cnt']]

,entity_id,ans_id,company_name,non_design_pct_apno_cnt
1706951,f254495135e355974c3390b08a879344,f039e90a-679c-4c50-ab06-72d03d496c4f,华为技术有限公司,57670
1481377,af85ee378b02ba0dc91ce645e7032f51,88160f04-ce97-4e32-ae41-e7ad897aaa17,"QUALCOMM, Inc.",36544
1469868,fbcc6cb268afb3595ef78e7a7fd56da1,1b7b903a-86f1-4889-9e32-bd85a208de67,Robert Bosch GmbH,33651
315391,c4d08d578953b636cd827c7d180f031a,10e4c90b-83bb-4abb-9b47-06c55a031cc3,Siemens AG,31779
1157671,0dbd3c4fa6b4f69048880d3770029954,f81142e5-de83-4ee5-bc84-b9bf4332a2fc,"Ericsson, Inc.",31657
...,...,...,...,...
828526,3eeb95aaf92c356ab27de552b26a27d7,077bd304-552e-4e3e-9603-03eb05576511,成都智库二八六一信息技术有限公司,0
828525,674d0e05a3a5b082de9223df73fd9b1d,36df14d1-1245-4341-aea6-f6b16489b66e,昆山众赢昌盛贸易有限公司,0
828524,318bf524046dab12ebcc909eed521c1e,eb1cf1e5-84da-474b-a2f7-eda056c3523a,None,0
828523,7ac2b5f7cdb62255ac295ec0407701de,6724575d-4188-47e0-b580-f8032f217cff,深圳市凯乐兴科技有限公司,0
2368322,f774c4ca18798080ede7bf2d47a6a7ac,None,安徽智农农业设备科技有限公司,0